### ISSUE TITLE
Bot does not start.

### ISSUE THREAD

**Issue by w0zol** [b0gotac/steam-lvlup-bot#15]
Hi,

I checked everything in the config file and it is 100 % correct.
Everything goes right while placing the bot files into the VPS but when I start it with : `forever start index.js` the bot doesn't go online.. I tried `forever start --minUptime 1000 --spinSleepTime 1000 index.js` but it doesn't work either.

**Best Regards,**
_w0zol_.

**Comment by GGrandma** [comment]
Are you receiving any errors? If so please comment them.

**Comment by w0zol** [comment]
@GGrandma no errors.. Can you send me your steam url or add me here [http://steamcommunity.com/id/wukz](url) so we can speak faster and hopefully get this to work.

Thank you for the response !

**Best Regards,**
_w0zol._

**Comment by w0zol** [comment]
# **! FIXED ! **

_Thanks @GGrandma for helping._

Bot not going online? Here is how to fix it  : [CLICK HERE ( github page )](https://github.com/b0gotac/steam-lvlup-bot/issues/16)
